version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    versioning-strategy: "increase"
    schedule:
      interval: "daily"
    groups:
      phpstan:
        dependency-type: "development"
        patterns:
          - "larastan/larastan"
          - "phpstan/*"
      dev-dependencies:
        dependency-type: "development"
      production-patches:
        dependency-type: "production"
        update-types: [ "patch" ]
    registries:
      - composer

registries:
  composer:
    type: composer-repository
    url: https://jfrogghdemo.jfrog.io/artifactory/api/composer/dependabot-php/
    username: thavaahariharangit@github.com
    password: "${{secrets.JFROG_ARTIFACTORY_TOKEN}}"
