version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "visma-verzuim/phx-php-dependency-updaters"
    groups:
      phpstan:
        dependency-type: "development"
        patterns:
          - "larastan/larastan"
          - "phpstan/*"
      dev-dependencies:
        dependency-type: "development"
      production-patches:
        dependency-type: "production"
        update-types: [ "patch" ]
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"